/**
 * Generates src/styles/generated/dark-text.css, which build-css.ts appends to the blueprint layer.
 *
 * Blueprint's dark rules lighten typography colors, for example
 * `oklch(from var(--bp-typography-color-muted) calc(l + 0.24) calc(c - 0.011) h)`, because Blueprint
 * keeps light values in some of those variables. The Clawscale bridge themes every one of them,
 * so the shift would stack and turn muted text almost white. This script copies each such
 * declaration without the shift. The copies keep Blueprint's selectors and follow its sheets in
 * the same layer, so they replace only those declarations and leave Blueprint's cascade alone.
 *
 * Run after a Blueprint upgrade: pnpm --filter @clawscale/react generate
 * test/styles.test.ts fails when the file is stale.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { DARK } from "@blueprintjs/core/lib/cjs/common/classes.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(join(root, "package.json"));
export const darkTextPath = join(root, "src", "styles", "generated", "dark-text.css");

const sheets = [
  "@blueprintjs/core/lib/css/blueprint.css",
  "@blueprintjs/select/lib/css/blueprint-select.css",
  "@blueprintjs/datetime/lib/css/blueprint-datetime.css",
  "@blueprintjs/table/lib/css/table.css",
];

const TYPOGRAPHY_SOURCE = "from var(--bp-typography-color-";
// oklch(from var(--bp-typography-color-muted) calc(l + 0.24) calc(c - 0.011) h), with an optional alpha
const SHIFTED =
  /oklch\(\s*from var\((--bp-typography-color-[a-z-]+)\)\s+calc\(l\s*[+-]\s*-?[\d.]+\)\s+(?:c|calc\(c\s*[+-]\s*-?[\d.]+\))\s+(?:h|calc\(h\s*[+-]\s*-?[\d.]+\))\s*(?:\/\s*([\d.]+%?)\s*)?\)/g;

const isDark = (selector: string) => selector.includes(`.${DARK}`) || selector.includes("[data-bp-color-scheme=dark]");

/** Style rules at the top level of a stylesheet. Rules inside at-rules are skipped. */
function topLevelRules(css: string): { selector: string; body: string }[] {
  const rules: { selector: string; body: string }[] = [];
  let depth = 0;
  let start = 0;
  let prelude = "";
  for (let i = 0; i < css.length; i++) {
    const char = css[i];
    if (char === "{") {
      if (depth === 0) {
        prelude = css.slice(start, i).trim();
        start = i + 1;
      }
      depth++;
    } else if (char === "}") {
      depth--;
      if (depth === 0) {
        if (!prelude.startsWith("@")) rules.push({ selector: prelude, body: css.slice(start, i) });
        start = i + 1;
      }
    } else if (char === ";" && depth === 0) {
      start = i + 1;
    }
  }
  return rules;
}

/** Splits a selector list on commas outside parentheses. */
function splitSelectors(list: string): string[] {
  const selectors: string[] = [];
  let depth = 0;
  let current = "";
  for (const char of list) {
    if (char === "(") depth++;
    if (char === ")") depth--;
    if (char === "," && depth === 0) {
      selectors.push(current);
      current = "";
    } else {
      current += char;
    }
  }
  selectors.push(current);
  return selectors.map((s) => s.trim().replace(/\s+/g, " ")).filter(Boolean);
}

export function renderDarkText(): string {
  const rules: string[] = [];
  for (const sheet of sheets) {
    const css = readFileSync(require.resolve(sheet), "utf8").replace(/\/\*[\s\S]*?\*\//g, "");
    for (const { selector, body } of topLevelRules(css)) {
      const dark = splitSelectors(selector).filter(isDark);
      if (dark.length === 0) continue;
      const declarations = body
        .split(";")
        .map((d) => d.trim().replace(/\s+/g, " "))
        .filter((d) => d.includes(TYPOGRAPHY_SOURCE) && !d.startsWith("--"))
        .map((d) => {
          const restated = d.replace(SHIFTED, (_match, variable: string, alpha?: string) =>
            alpha ? `oklch(from var(${variable}) l c h / ${alpha})` : `var(${variable})`,
          );
          if (/calc\([lch] /.test(restated) && restated.includes(TYPOGRAPHY_SOURCE)) {
            throw new Error(`dark text: unknown color format in ${selector.trim()}: ${d}`);
          }
          return restated === d ? undefined : restated.replace(/^([a-z-]+)\s*:\s*/, "$1: ");
        })
        .filter((d): d is string => d !== undefined);
      if (declarations.length === 0) continue;
      rules.push(`${dark.join(",\n")} {\n${declarations.map((d) => `  ${d};`).join("\n")}\n}`);
    }
  }
  return [
    "/* Generated by scripts/generate-dark-text.ts from Blueprint's stylesheets. Do not edit. */",
    "",
    rules.join("\n\n"),
    "",
  ].join("\n");
}

function main() {
  const next = renderDarkText();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(darkTextPath, "utf8");
    } catch {}
    if (current !== next) {
      console.error("Stale dark text colors. Run: pnpm --filter @clawscale/react generate");
      process.exit(1);
    }
    return;
  }
  mkdirSync(dirname(darkTextPath), { recursive: true });
  writeFileSync(darkTextPath, next);
  console.log("wrote src/styles/generated/dark-text.css");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
