/**
 * Generates src/generated/*.ts: explicit, named re-exports of every Blueprint runtime export,
 * each file marked "use client" so Next.js server components can import them.
 *
 * Next.js rejects `export *` inside a "use client" module, so names must be listed.
 * Run after any Blueprint upgrade: `pnpm --filter @clawscale/react generate`.
 * `test/exports.test.ts` fails when these files are stale.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(join(root, "package.json"));

export const blueprintEntries = [
  { file: "core", pkg: "@blueprintjs/core" },
  { file: "select", pkg: "@blueprintjs/select" },
  { file: "datetime", pkg: "@blueprintjs/datetime" },
  { file: "table", pkg: "@blueprintjs/table" },
  { file: "icons", pkg: "@blueprintjs/icons" },
] as const;

/**
 * Blueprint exports that src/components replaces with a drop-in component of the same name.
 * They are left out of the generated files so the Clawscale version is the only one exported.
 */
export const replacedExports: Readonly<Record<string, readonly string[]>> = {
  "@blueprintjs/core": ["KeyComboTag"],
};

/** Runtime export names of a Blueprint package, sorted. */
export function runtimeExports(pkg: string): string[] {
  const mod = require(pkg) as Record<string, unknown>;
  return Object.keys(mod)
    .filter((name) => name !== "__esModule" && name !== "default")
    .sort();
}

export function renderEntry(pkg: string): string {
  const version = (require(`${pkg}/package.json`) as { version: string }).version;
  const replaced = new Set(replacedExports[pkg] ?? []);
  const names = runtimeExports(pkg).filter((name) => !replaced.has(name));
  return [
    '"use client";',
    "",
    `// Generated by scripts/generate-exports.ts from ${pkg}@${version}. Do not edit.`,
    "",
    "export {",
    ...names.map((name) => `  ${name},`),
    `} from "${pkg}";`,
    `export type * from "${pkg}";`,
    "",
  ].join("\n");
}

function main() {
  const check = process.argv.includes("--check");
  const outDir = join(root, "src", "generated");
  mkdirSync(outDir, { recursive: true });
  const stale: string[] = [];
  for (const { file, pkg } of blueprintEntries) {
    const path = join(outDir, `${file}.ts`);
    const next = renderEntry(pkg);
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {}
    if (current === next) continue;
    if (check) stale.push(path);
    else writeFileSync(path, next);
  }
  if (stale.length > 0) {
    console.error(`Stale generated exports:\n${stale.join("\n")}\nRun: pnpm --filter @clawscale/react generate`);
    process.exit(1);
  }
  console.log(check ? "generated exports are up to date" : "wrote src/generated/*.ts");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
