/**
 * Generates src/styles/generated/table-borders.css.
 *
 * @blueprintjs/table draws every grid line as a box-shadow in fixed colors, which vanish
 * on Clawscale's dark surfaces. This script copies each of those rules and swaps the line
 * colors for --cs-color-border, keeping Blueprint's offsets (including the 3px frozen dividers).
 *
 * Run after a Blueprint upgrade: pnpm --filter @clawscale/react generate
 * test/styles.test.ts fails when the file is stale.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(join(root, "package.json"));
export const tableBordersPath = join(root, "src", "styles", "generated", "table-borders.css");

const LINE_COLOR = /rgba\(\s*(17,\s*20,\s*24|255,\s*255,\s*255),\s*0?\.\d+\s*\)/g;

export function renderTableBorders(): string {
  const css = readFileSync(require.resolve("@blueprintjs/table/lib/css/table.css"), "utf8");
  const rules: string[] = [];
  for (const [, selector = "", body = ""] of css.matchAll(/([^{}@]+)\{([^{}]*)\}/g)) {
    const shadow = /box-shadow:\s*([^;]+)/.exec(body)?.[1];
    if (!shadow || !LINE_COLOR.test(shadow)) continue;
    LINE_COLOR.lastIndex = 0;
    const selectors = selector
      .split(",")
      .map((s) => s.trim().replace(/\s+/g, " "))
      .join(",\n");
    rules.push(`${selectors} {\n  box-shadow: ${shadow.trim().replace(LINE_COLOR, "var(--cs-color-border)")};\n}`);
  }
  return [
    "/* Generated by scripts/generate-table-borders.ts from @blueprintjs/table. Do not edit. */",
    "",
    rules.join("\n\n"),
    "",
  ].join("\n");
}

function main() {
  const next = renderTableBorders();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(tableBordersPath, "utf8");
    } catch {}
    if (current !== next) {
      console.error("Stale table borders. Run: pnpm --filter @clawscale/react generate");
      process.exit(1);
    }
    return;
  }
  mkdirSync(dirname(tableBordersPath), { recursive: true });
  writeFileSync(tableBordersPath, next);
  console.log("wrote src/styles/generated/table-borders.css");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
