/** Class names used by Clawscale components. Safe in server components. */
export const ClawscaleClasses = {
  DELTA: "cs-delta",
  DELTA_ICON: "cs-delta-icon",
  LABEL: "cs-label",
  METRIC: "cs-metric",
  METRIC_CAPTION: "cs-metric-caption",
  METRIC_FOOTER: "cs-metric-footer",
  METRIC_LABEL: "cs-metric-label",
  METRIC_TREND: "cs-metric-trend",
  METRIC_UNIT: "cs-metric-unit",
  METRIC_VALUE: "cs-metric-value",
  MONOSPACE: "cs-monospace",
  NUMERIC: "cs-numeric",
  PROPERTY: "cs-property",
  PROPERTY_LABEL: "cs-property-label",
  PROPERTY_LIST: "cs-property-list",
  PROPERTY_VALUE: "cs-property-value",
  SPARKLINE: "cs-sparkline",
  SPARKLINE_AREA: "cs-sparkline-area",
  SPARKLINE_DOT: "cs-sparkline-dot",
  SPARKLINE_LINE: "cs-sparkline-line",
  STATUS_BAR: "cs-status-bar",
  STATUS_BAR_ITEM: "cs-status-bar-item",
  STATUS_BAR_SPACER: "cs-status-bar-spacer",
  VISUALLY_HIDDEN: "cs-visually-hidden",
} as const;
